---
# tasks file for microk8s
- name: Install MicroK8s, kubectl via Snap
  community.general.snap:
    name:
      - microk8s
      - kubectl
    classic: true
  become: true
  register: install_microk8s_result

- name: Add user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    groups: microk8s
    append: true
  become: true
  register: add_to_microk8s_group_result

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection
  when: add_to_microk8s_group_result.changed

- name: Wait for microk8s to be ready (up to 10 minutes)
  ansible.builtin.shell: /snap/bin/microk8s status --wait-ready --timeout 600
  when: install_microk8s_result.changed

- name: Configure kubectl for user
  ansible.builtin.shell: "/snap/bin/microk8s kubectl config view --raw > ~/.kube/config"
  when: install_microk8s_result.changed

- name: Enable storage and ingress module in microk8s
  ansible.builtin.shell: /snap/bin/microk8s enable hostpath-storage ingress rbac
  become: true
  when: install_microk8s_result.changed

- name: Change permissions of kubectl config file
  ansible.builtin.file:
    path: ~/.kube/config
    mode: go-r
  when: install_microk8s_result.changed

- name: Install kubernetes python module
  ansible.builtin.package:
    name: python3-kubernetes
    state: present
  become: true

- name: Apply Kubernetes files to target
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '{{ item.filename }}') | from_yaml }}"
    namespace: default
  loop: "{{ files | default([], true) }}"

