apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  tls:
    - hosts:
      - securityplayground.projekte.it.hs-worms.de
      secretName: secplay-ssl
  rules:
  - host: securityplayground.projekte.it.hs-worms.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secplay-website
            port:
              number: 80