stages:
  - lint
  - syntax-check
  - deploy

variables:
  ANSIBLE_INVENTORY: 'ansible/setup-k8s/inventory.ini'
  ANSIBLE_PLAYBOOK: 'ansible/setup-k8s/playbook.yml'       

lint:
  stage: lint
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y ansible ansible-lint sshpass
  script:
    - echo "Starting Lint"
    - ansible-lint --profile min $ANSIBLE_PLAYBOOK
    - echo "Ending Lint"
  only:
    - merge_requests
    - main

syntax-check:
  stage: syntax-check
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y ansible sshpass
  script:
    - echo "Starting Syntax Check"
    - ansible-playbook $ANSIBLE_PLAYBOOK --syntax-check 
    - echo "Ending Syntax Check"
  only:
    - merge_requests
    - main



deployment:
   stage: deploy
   image: debian:12
   before_script:
     - apt-get update && apt-get install -y ansible sshpass git iputils-ping -y
   script:
     - echo "Checking for changes in all.yml..."
     - ping 143.93.245.88 -c 5
     - |
       if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q 'group_vars/all.yml'; then
         echo "'all.yml' has changed, executing Ansible command..."
         ansible all -i inventory.ini -m include_role -a name=helm_deploy -e @group_vars/all.yml -K
       else
         echo "Starting Deployment"
         ansible-playbook $ANSIBLE_PLAYBOOK --inventory $ANSIBLE_INVENTORY 
         echo "Ending Deployment"
       fi
     - echo "Deployment step concluded."
   only:
     - main
