stages:
  - lint
  - deployment

variables:
  ANSIBLE_INVENTORY: 'ansible/setup-k8s/inventory.ini'
  ANSIBLE_PLAYBOOK: 'ansible/setup-k8s/playbook.yml'       

lint:
  stage: lint
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y ansible ansible-lint sshpass
  script:
    - echo "Starting Syntax Check"
    - ansible-playbook $ANSIBLE_PLAYBOOK --syntax-check
    - echo "Ending Syntax Check"
    - echo "Starting Lint"
    - ansible-lint --profile min $ANSIBLE_PLAYBOOK
    - echo "Ending Lint"
  only:
    - main
    - merge_requests

deployment:
  stage: deployment
  image: debian:12
  before_script: 
    - apt-get update && apt-get install -y ansible sshpass git iputils-ping
  script:
    - >
      if [ "$CI_PROJECT_NAME" != "codebase-local" ]; then
        echo "This is not the 'codebase-local' repository, skipping deployment."
        exit 0
      fi
    - echo "Checking for changes in all.yml..."
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q 'group_vars/all.yml'; then
        echo "'all.yml' has changed, executing Ansible command..."
        ansible all -i $ANSIBLE_INVENTORY -m include_role -a name=helm_deploy -e @group_vars/all.yml -K
      else
        echo "Starting Deployment"
        ansible-playbook $ANSIBLE_PLAYBOOK --inventory $ANSIBLE_INVENTORY 
        echo "Ending Deployment"
      fi
    - echo "Deployment step concluded."
  only:
    - main
    - merge_requests

