stages:
  - lint
  - deployment

variables:
  ANSIBLE_INVENTORY: 'ansible/setup-k8s/inventory.ini'
  ANSIBLE_PLAYBOOK: 'ansible/setup-k8s/playbook.yml'       

lint:
  stage: lint
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y ansible ansible-lint sshpass
  script:
    - echo "Starting Syntax Check"
    - ansible-playbook $ANSIBLE_PLAYBOOK --syntax-check
    - echo "Ending Syntax Check"
    - echo "Starting Lint"
    - ansible-lint --profile min $ANSIBLE_PLAYBOOK
    - echo "Ending Lint"
  only:
    - main
    - merge_requests

deployment:
  stage: deployment
  image: debian:12
  before_script: 
    - apt-get update && apt-get install -y ansible sshpass git iputils-ping
    - |
      if [ "$CI_PROJECT_NAME" != "codebase-local" ]; then
        command -v ssh-agent >/dev/null || ( apt-get install -y openssh-client )
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_HOST_KEY" | tr -d '\r' >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      fi
  script:
    - ssh -o StrictHostKeyChecking=no student@$VM_IPADDRESS "hostname && echo 'Welcome!!!' > welcome.txt"
  only:
    - main
    - merge_requests

