stages:
  - lint
  - syntax-check
  # - dry-run
  # - deployment

variables:
  ANSIBLE_INVENTORY: 'ansible/setup-k8s/inventory.ini'
  ANSIBLE_PLAYBOOK: 'ansible/setup-k8s/playbook.yml'       

lint:
  stage: lint
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y ansible ansible-lint sshpass
  script:
    - echo "Starting Lint"
    - ansible-lint $ANSIBLE_PLAYBOOK
    - echo "Ending Lint"
  only:
    - merge_requests
    - main

syntax-check:
  stage: syntax-check
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y ansible sshpass
  script:
    - echo "Starting Syntax Check"
    - ansible-playbook $ANSIBLE_PLAYBOOK --syntax-check 
    - echo "Ending Syntax Check"
  only:
    - merge_requests
    - main

# dry-run:
#   stage: dry-run
#   image: debian:12
#   before_script:
#     - apt-get update && apt-get install -y ansible sshpass
#   script:
#     - echo "Starting Dry Run"
#     - ansible-playbook $ANSIBLE_PLAYBOOK --check --inventory $ANSIBLE_INVENTORY 
#     - echo "Ending Dry Run"
#   only:
#     - merge_requests
#     - master


# deployment:
#   stage: deploy
#   image: debian:12
#   before_script:
#     - apt-get update && apt-get install -y ansible sshpass
#   script:
#     - echo "Starting Deployment"
#     - ansible-playbook $ANSIBLE_PLAYBOOK --inventory $ANSIBLE_INVENTORY 
#     - echo "Ending Deployment"
#   only:
#     - master