---
# tasks file for setup-snapd
- name: Install snapd
  ansible.builtin.apt:
    name:
      - snapd
    state: present
    update_cache: true
  become: true
  register: install_snapd_result

- name: Ensure snap is started and enabled on boot
  ansible.builtin.systemd:
    enabled: true
    name: snapd
    state: started
  become: true

- name: Reload udev
  ansible.builtin.service:
    name: udev
    state: restarted
  become: true
  when: install_snapd_result.changed

- name: Ensure snap core is installed
  community.general.snap:
    name: core
    state: present
  become: true
