---
# DOWNLOAD HELM REPOSITORYS
repositories:
  - repo_name: "bitnami"
    repo_url: "https://charts.bitnami.com/bitnami"
  - repo_name: "gitlab-rlp"
    repo_url: "https://gitlab.rlp.net/api/v4/projects/39843/packages/helm/stable"
    repo_username: "gitlab+deploy-token-247"
    repo_password: "gldt-G4NVnsZx8yx56MpXRvsC"
  - repo_name: "gitlab-rlp-fullstack"
    repo_url: "https://gitlab.rlp.net/api/v4/projects/40083/packages/helm/stable"
    repo_username: "ansible"
    repo_password: "gldt-e6fVARFitCULWyd-29oA"
  - repo_name: "dapr"
    repo_url: "https://dapr.github.io/helm-charts/"
  - repo_name: "securecodebox"
    repo_url: "https://charts.securecodebox.io/"
  - repo_name: "portainer"
    repo_url: "https://portainer.github.io/k8s/"

# --------------------
# INSTALL HELM CHARTS
deployments:

  # DEPLOY DAPR VIA HELM
  - name: "dapr"
    chart_ref: "dapr/dapr"
    release_namespace: "dapr-system"
    create_namespace: true
    wait: true

# --------------------
# DEPLOY OWN HELM CHARTS (Port 30000 - 32000)
  - name: "secplay-website"
    chart_ref: "gitlab-rlp/secplay-website" # Port = 80 (ingress)

  # WEBSHOP FROM FULLSTACK PROJECT
  - name: "webshop"
    chart_ref: "gitlab-rlp-fullstack/webshop"
    set_values:
     - value: "frontend.nodePort=32000" # Port

# --------------------
# DEPLOY HELM CHARTS FROM REMOTE REPOSITORY (Port 32001 - 32767)

  # WORDPRESS
  # - name: "wordpress-latest"
  #   chart_ref: "bitnami/wordpress"
  #   set_values:
  #    - value: "overrideDatabaseSettings=true"
  #    - value: "persistence.enabled=false"
  #    - value: "service.nodePorts.http=32000" # Port

  # POSTGRESQL
  # - name: "postgresql"
  #   chart_ref: bitnami/postgresql
  #   set_values:
  #     - value: "primary.service.type=LoadBalancer"
  #     - value: "primary.service.nodePorts.postgresql=32010" # Port

  # MARIADB
  # - name: "mariadb"
  #   chart_ref: bitnami/mariadb
  #   set_values:
  #     - value: "primary.service.type=LoadBalancer"
  #     - value: "primary.service.nodePorts.mysql=32020" # Port
  #     - value: "auth.rootPassword=sTuD3nT#"

  # PHPMYADMIN
  # - name: "phpmyadmin"
  #   chart_ref: bitnami/phpmyadmin
  #   set_values:
  #     - value: "service.type=LoadBalancer"
  #     - value: "service.nodePorts.http=32030" # Port
  #     - value: "replicas=2"

  # APACHE
  # - name: "apache"
  #   chart_ref: bitnami/apache
  #   set_values:
  #     - value: "service.type=LoadBalancer" 
  #     - value: "service.nodePorts.http=32040" # Port

  # JUICE-SHOP
  - name: "juice-shop"
    chart_ref: "gitlab-rlp/juiceshop"
    set_values:
      - value: "service.type=LoadBalancer"
      - value: "service.nodePort=32050" # Port

  # PORTAINER
  - name: "portainer"
    chart_ref: "portainer/portainer"
    create_namespace: true
    release_namespace: "portainer"
  
  # STARTSPHERE
  - name: "startsphere"
    chart_ref: "gitlab-rlp/startsphere"
    set_values:
      - value: "service.type=LoadBalancer"
      - value: "service.nodePort=32070" # Port

  # KIOPTRIX
  - name: "kioptrix"
    chart_ref: "gitlab-rlp/kioptrix"
    set_values:
      - value: "service.type=LoadBalancer"

# --------------------
# FILES
files:
  - filename: "docker_registry_config.yaml"
  - filename: "docker_registry_config_fullstack.yaml"
  - filename: "http-ingress.yaml"

# --------------------
# SYSTEM ARCHITECTURE
arch: amd64

# --------------------
# AMOUNT OF USER ACCOUNTS IN THE CLUSTER
usercount: 3