- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present

- name: Get the latest stable version of KubeVirt
  ansible.builtin.shell:
    cmd: curl -s https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt
  register: kubevirt_version_raw

- name: Set the KubeVirt version as a fact
  ansible.builtin.set_fact:
    kubevirt_version: "{{ kubevirt_version_raw.stdout | trim }}"

- name: Download KubeVirt Operator YAML
  ansible.builtin.get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-operator.yaml"
    dest: "/tmp/kubevirt-operator.yaml"

- name: Install KubeVirt Operator
  kubernetes.core.k8s:
    state: present
    src: "/tmp/kubevirt-operator.yaml"

- name: Download KubeVirt Custom Resource (CR) YAML
  ansible.builtin.get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-cr.yaml"
    dest: "/tmp/kubevirt-cr.yaml"

- name: Install KubeVirt Custom Resource (CR)
  kubernetes.core.k8s:
    state: present
    src: "/tmp/kubevirt-cr.yaml"
  
- name: Remove temporary KubeVirt Operator YAML
  ansible.builtin.file:
    state: absent
    path: "/tmp/kubevirt-operator.yaml"

- name: Remove temporary KubeVirt CR YAML
  ansible.builtin.file:
    state: absent
    path: "/tmp/kubevirt-cr.yaml"
    
- name: Verify KubeVirt Installation
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kubevirt
  register: kubevirt_pods


