- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present
  become: true

- name: Get the latest stable version of KubeVirt
  ansible.builtin.shell: >
    curl -s https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt
  register: kubevirt_version_raw

- name: Set the KubeVirt version as a fact
  ansible.builtin.set_fact:
    kubevirt_version: "{{ kubevirt_version_raw.stdout }}"

- name: Download KubeVirt Operator manifest
  ansible.builtin.get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-operator.yaml"
    dest: ~/kubevirt-operator.yaml
    mode: 0644

- name: Apply KubeVirt Operator manifest
  kubernetes.core.k8s:
    state: present
    src: ~/kubevirt-operator.yaml

- name: Download KubeVirt Custom Resource (CR)
  ansible.builtin.get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-cr.yaml"
    dest: ~/kubevirt-cr.yaml
    mode: 0644

- name: Apply KubeVirt Custom Resource (CR)
  kubernetes.core.k8s:
      state: present
      src: ~/kubevirt-cr.yaml

- name: Verify KubeVirt Installation
  ansible.builtin.command:
    cmd: "/snap/bin/microk8s kubectl get all -n kubevirt"
  register: kubevirt_pods
  become: true

- name: Show KubeVirt Pods
  ansible.builtin.debug:
    var: kubevirt_pods.stdout_lines

