---
# tasks file for helm
- name: Download helm binary
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v3.14.0-linux-{{ arch }}.tar.gz"
    dest: "/tmp/helm-v3.14.0-linux-{{ arch }}.tar.gz"
  become: true

- name: Extract helm binary
  ansible.builtin.unarchive:
    src: "/tmp/helm-v3.14.0-linux-{{ arch }}.tar.gz"
    dest: /tmp
    remote_src: true
  become: true

- name: Move helm binary to /usr/local/bin
  copy:
    src: /tmp/linux-{{ arch }}/helm
    dest: /usr/local/bin/helm
    mode: "0755"
    remote_src: true
  become: true

- name: Install python3-yaml needed for helm
  ansible.builtin.apt:
    name: python3-yaml
    state: present
  become: true
