---
# tasks file for helm-deploy
- name: "Add helm repos"
  kubernetes.core.helm_repository:
    name: "{{ item.key }}"
    repo_url: "{{ item.value }}"
  become: true
  loop: "{{ repos | dict2items }}"

- name: "Deploy helm charts"
  kubernetes.core.helm:
    name: "{{ item.key }}"
    chart_ref: "{{ item.value }}"
    release_namespace: "{{ namespace }}"
  become: true
  environment:
    KUBECONFIG: /home/{{ user }}/.kube/config
  loop: "{{ deployments | dict2items }}"
